### PR TITLE
Refactoring to compatibility with rabbitmq/rabbitmq-stomp/pull/51

### LINKED ISSUE #30: Stomp processor changes broke Web STOMP
This merge https://github.com/rabbitmq/rabbitmq-stomp/commit/d0393355e856158131fa7d0fbcf5f5e1d822abde from https://github.com/rabbitmq/rabbitmq-stomp/issues/6 with PR at https://github.com/rabbitmq/rabbitmq-stomp/pull/51

Currently Web STOMP does not work at all. The undef error here https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/src/rabbit_ws_client_sup.erl#L67 results in the SockJS application crashing entirely.

Not sure how the code should be changed.

### PR DESCRIPTION
**Pull request by hairyhum**
Fixes #30 
@essen can you check please if everything is OK with termination?

### CODE REVIEW

**Comment by essen** [comment]
You can try rabbitmq-web-stomp-examples, there should be 6 examples, if those and the tests work it should be good.

I will try on my side also.

**Comment by hairyhum** [comment]
At least on my machine it's working.

**Comment by essen** [comment]
The tests pass here, having issues with examples but that's probably unrelated to this (my changes are probably the cause). If examples work for you I'm OK with this PR. +1

**Comment by essen** [comment]
Disregard previous comment, I was having issues with my brain, examples work fine for me too.

**Comment by michaelklishin** [comment]
@hairyhum thank you for stepping in to fix it so quickly.

**Pull request merged**
